name: Build develop
on:
  push:
    branches:
      - develop
jobs:
  BuildProject:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Build
        run: ./gradlew build
