name: Setup Java and Execute Command

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string

jobs:
  setup-java-and-execute-command:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Execute command
        run: ${{ inputs.command }}
