name: Verification pull request
on: pull_request

jobs:
  Build:
    uses: ./.github/workflows/setup_java_and_execute_command.yml
    with:
      command: ./gradlew assemble
  Lint:
    uses: ./.github/workflows/setup_java_and_execute_command.yml
    with:
      command: ./gradlew lint
  Ktlint:
    uses: ./.github/workflows/setup_java_and_execute_command.yml
    with:
      command: ./gradlew ktlintCheck
  Test:
    uses: ./.github/workflows/setup_java_and_execute_command.yml
    with:
      command: ./gradlew test
